version: "3.9"

services:
  bot:
    image: python:3.11-slim
    working_dir: /app
    volumes:
      - ./:/app
    env_file:
      - .env
    command: bash -lc "pip install --no-cache-dir -r requirements.txt && python -m app.main"
