name: Semantic Search Tests

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]
  schedule:
    # Запуск щодня о 6:00 UTC для перевірки API
    - cron: "0 6 * * *"

jobs:
  semantic-search-test:
    runs-on: ubuntu-latest

    env:
      NODE_ENV: test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Create test database
        run: |
          mkdir -p data
          touch data/bot.db

      - name: Test semantic search (without API key)
        run: |
          echo "Тестування семантичного пошуку без API ключа..."
          node test-semantic-search.js || true

      - name: Test language service
        run: |
          echo "Тестування мовного сервісу..."
          node test-phrases.js || true

      - name: Test database operations
        run: |
          echo "Тестування операцій бази даних..."
          node -e "
            const dbService = require('./src/bot/services/database');
            console.log('База даних ініціалізована');
            console.log('Тест пройшов успішно');
          " || true

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            *.log
            data/bot.db
          retention-days: 7
